### ISSUE TITLE
Is there any metric that measures the performance of SIR model?

### ISSUE THREAD

**Issue by ucalyptus** [aryadas98/covid19-india-predictor#1]
like R2 and adjusted R2

**Comment by aryadas98** [comment]
I haven't worked on formalizing a metric. As I have declared on the site, this is just a hobby project. However, one way to measure the consistency of the model is to see whether the coefficients vary too much or stay constant. Fortunately it turns out the coefficients for recoveries and deaths are fairly constant. The coefficient for new cases is more like a constant plus a sin wave. I will post the graphs here soon when I am on my laptop.

**Comment by ucalyptus** [comment]
ok

**Comment by aryadas98** [comment]
Hi @ucalyptus these are the graphs of the coefficients.
Please check https://covid19-india-predictor.netlify.com/how-it-works/ to know what each coefficient means.

![image](https://user-images.githubusercontent.com/10235437/79023688-90a4f380-7b9e-11ea-8ab0-74089973bf01.png)

![image](https://user-images.githubusercontent.com/10235437/79023744-ac0ffe80-7b9e-11ea-9755-747416ca0e3c.png)

![image](https://user-images.githubusercontent.com/10235437/79023773-bb8f4780-7b9e-11ea-8f8a-753b677e2fc5.png)
